package views;

import java.awt.Color;

public class MyMessage {
	public static final Color COLOR_1 = Color.decode("#F99949");
	public static final String GET_OPTION ="Ingrese su opcion";
	public static final String INVALID_OPTION ="¡¡¡¡Opcion invalida, Ingresa un numero!!!!";
	public static final String THANKS ="Gracias por usar la aplicacion! Hasta Luego";
	public static final String IN_NAME ="Ingrese su nombre";
	public static final String IN_NAME_PRODUCT ="Ingrese nombre del producto";
	public static final String IN_CC ="Ingrese cedula de ciudadania";
	public static final String IN_PRICE ="Ingrese precio";
	public static final String IN_TIME ="Ingrese tiempo";
	public static final String IN_SIZE ="Ingrese tamaño";
	public static final String MENU_PRODUCTS ="Ver Menu";
	public static final String INFORMATION ="Informacion del contacto:";
	public static final String SINGS_RIGHT =">>> ";
	public static final String SINGS_LEFT =" <<< \n";
	public static final String MENU ="Que desea hacer? \n   1: Ver menu\n   2: Agregar producto al pedido\n   3: Quitar producto del pedido\n   4: Ver productos pedidos\n   5: Ver turno\n   6: Ver tiempo de coccion de pedido\n   7: Salir";
	public static final String MENU_A ="Que desea hacer? \n   1: Ver menu\n   2: Crear producto\n   3: Eliminar producto\n   4: Ver cientes por atender\n   5: Ver clientes atendidos\n   6: Ver ventas totales\n   7: Atender cliente\n   8: Salir";
	public static final String MENU_AC ="Usted es? \n   1: Cliente\n   2: Administrador\n";
	public static final String NOT_IMPLEMENTED ="No implementado\n";
	public static final String MINUTES ="Minutos\n";
	public static final String SHOW_TURN ="Turno";
	public static final String SHOW_TIME ="El pedido tarde en hacerce aproximadamente: \n";
	public static final String CLIENTS_TO_ATTEND ="Clientes por atender";
	public static final String CLIENTS_ATTEND ="Clientes Atendendidos";
	public static final String TOTAL_SALES ="Ver Total de ventas";
	public static final String ATTEND_CLIENT ="Atender Cliente";
	public static final String BURGER_SHOT ="BURGER SHOT: Comidas rapidas";
	public static final String BURGER_SHOT_PATH ="Resources/Burger Shot.png";
	public static final String MENU_PATH ="Resources/menu.png";
	public static final String FONT_RUBIK ="rubik";
	public static final String ADD_PATH ="Resources/Add.png";
	public static final String DELETE_PATH ="Resources/Delete.png";
	public static final String BILL_PATH ="Resources/Bill.png";
	public static final String TURN_PATH ="Resources/Turn.png";
	public static final String TIME_PATH ="Resources/Time.png";
	public static final String BACK_PATH ="Resources/back.png";
	public static final String LOGO ="Resources/Shot.png";
	public static final String ADMIN_PATH ="Resources/admin.png";
	public static final String CLIENT_PATH ="Resources/client.png";
	public static final String ATTEND_PATH ="Resources/atender.png";
	public static final String FINE_PATH ="Resources/fine.png";
	public static final String SALE_PATH ="Resources/sale.png";
	public static final String ADMIN ="Entrar como Administrador";
	public static final String CLIENT ="Entrar como Cliente";
	public static final String ADD_PRODUCT ="Agregar Producto";
	public static final String DELETE_PRODUCT ="Borrar Producto";
	public static final String SEE_BILL ="Ver Factura";
	public static final String SEE_TURN ="Ver Turno";
	public static final String SEE_TIME ="Ver Tiempo";
	public static final String WELCOME ="Bienvenidos                            ";
	public static final String ACCEPT ="Aceptar";
	public static final String CANCEL ="Cancelar";
	public static final String EMPTY ="";
	public static final String DELETE ="Borrar";
	public static final String ADD ="Agregar";
	public static final String REGISTER ="Registrarse";
	public static final String REGISTER_PATH ="Resources/resgiter.png";

}
