package controllers;

public enum Commands {

	SHOW_LIST, ADD_PRODUCT, CREATE_PRODUCT, DELETE_PRODUCT, SHOW_CLIENTS_TO_ATTEND, SHOW_CLIENTS_ATTEND, SEE_TIME, SEE_TURN, 
	ATTEND_CLIENT, SHOW_TOTAL_SALES, BILL, ADMIN, CLIENT, DELETE_PRODUCT_ADMIN;
}
